# ═══════════════════════════════════════════════════════════════════════════════
# VITALO ANALYSIS OPTIONS
# ═══════════════════════════════════════════════════════════════════════════════
#
# This file configures the analyzer for static analysis of Dart code.
# Run: flutter analyze
#
# ┌───────────────────────────────────────────────────────────────────────────┐
# │                    ARCHITECTURAL IMPORT RULES                              │
# ├───────────────────────────────────────────────────────────────────────────┤
# │  Feature code (lib/features/**) MUST:                                     │
# │  • Import 'package:vitalo/design/design.dart' for all design primitives   │
# │  • NOT import flutter/material.dart or flutter/cupertino.dart directly    │
# │  • NOT import internal design files (tokens/, adaptive/ internals)        │
# │                                                                           │
# │  Run: dart run tool/check_imports.dart                                    │
# │  This script enforces the import architecture at CI/pre-commit time.      │
# └───────────────────────────────────────────────────────────────────────────┘
#
# ═══════════════════════════════════════════════════════════════════════════════

include: package:flutter_lints/flutter.yaml

analyzer:
  # Treat specific issues as errors to enforce code quality
  errors:
    # Treat unused imports as warnings (default is info)
    unused_import: warning
    # Treat missing return as error
    missing_return: error
    # Dead code should be cleaned up
    dead_code: warning

linter:
  rules:
    # ═══════════════════════════════════════════════════════════════════════
    # IMPORT DISCIPLINE
    # ═══════════════════════════════════════════════════════════════════════

    # Prefer relative imports within lib/ for internal consistency
    prefer_relative_imports: true

    # Avoid importing implementation details
    implementation_imports: true

    # ═══════════════════════════════════════════════════════════════════════
    # CODE QUALITY
    # ═══════════════════════════════════════════════════════════════════════

    # Enforce const where possible (performance + immutability)
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Clean code practices
    avoid_print: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Type safety
    avoid_dynamic_calls: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
